### PR TITLE
fix compile

### PR DESCRIPTION
**Pull request by iacore**

### CODE REVIEW

**Comment by yasukata** [comment]
Thank you for sending the patch.

Could you provide the following information so that I can have a better understanding of it?

- Linux distribution and its version (e.g., Ubuntu 22.04)
- CPU (e.g., Intel Xeon E5-2640)
- Output from the command ```ld --version```
- Error message shown by the compiler
- What was the issue of the current version?
- How does the patch fix the issue?
- Are [the deletion of line 15 in Makefile](https://github.com/yasukata/zpoline/pull/18/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L15) and [the two lines added after line 31 of main.c](https://github.com/yasukata/zpoline/pull/18/files#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ecR32-R33) necessary?

**Comment by iacore** [comment]
> * Linux distribution and its version (e.g., Ubuntu 22.04)

uh, Artix. rolling release.

> * CPU (e.g., Intel Xeon E5-2640)

generic amd64.

> * Output from the command `ld --version`

```
❯ ld --version
GNU ld (GNU Binutils) 2.42.0
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

> * Error message shown by the compiler

```
❯ make
/bin/sh: line 1: test: 242.0: integer expression expected
/bin/sh: line 1: test: 242.0: integer expression expected
gcc -O3 -pipe -g -rdynamic -Werror -Wall -Wunused-function -Wextra -shared -fPIC -DSUPPLEMENTAL__REWRITTEN_ADDR_CHECK   -c -o main.o main.c
In file included from /usr/include/dis-asm.h:36,
                 from main.c:32:
/usr/include/bfd.h:36:2: error: #error config.h must be included before this header
   36 | #error config.h must be included before this header
      |  ^~~~~
```

I can't find `config.h`.

> * What was the issue of the current version?

It can't build.

> * How does the patch fix the issue?

uh.. it can build now.

> * Are [the deletion of line 15 in Makefile](https://github.com/yasukata/zpoline/pull/18/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L15) and [the two lines added after line 31 of main.c](https://github.com/yasukata/zpoline/pull/18/files#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ecR32-R33) necessary?

line 15: no.

two lines added: yes. it's a stand-in for `config.h`.

**Comment by yasukata** [comment]
I confirmed that your patch fixes the issues on Artix. So, I merged your changes.

Thank you very much for providing the patch.

**Comment by iacore** [comment]
You're welcome :)

**Pull request merged**
